/// This file is auto-generated by `static-automata`. Do not edit.
pub struct Date {
	state: u32,
}
impl Date {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 27u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 9u32,
				'1' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'1'..='9' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='2' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'-' => 12u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 13u32,
				'1'..='2' => 14u32,
				'3' => 15u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='9' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='1' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'+' | '-' => 17u32,
				'Z' => 18u32,
				_ => return false,
			},
			17u32 => match token {
				'0' => 19u32,
				'1' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='9' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='3' => 21u32,
				'4' => 22u32,
				_ => return false,
			},
			21u32 => match token {
				':' => 23u32,
				_ => return false,
			},
			22u32 => match token {
				':' => 24u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='5' => 26u32,
				_ => return false,
			},
			24u32 => match token {
				'0' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				'0' => 18u32,
				_ => return false,
			},
			26u32 => match token {
				'0'..='9' => 18u32,
				_ => return false,
			},
			27u32 => match token {
				'0'..='9' => 28u32,
				_ => return false,
			},
			28u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 16u32 | 18u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DateTime {
	state: u32,
}
impl DateTime {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 48u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 9u32,
				'1' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'1'..='9' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='2' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'-' => 12u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 13u32,
				'1'..='2' => 14u32,
				'3' => 15u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='9' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='1' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'T' => 17u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='1' => 18u32,
				'2' => 19u32,
				_ => return false,
			},
			18u32 => match token {
				'0'..='9' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='3' => 20u32,
				'4' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				':' => 22u32,
				_ => return false,
			},
			21u32 => match token {
				':' => 23u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='5' => 41u32,
				_ => return false,
			},
			23u32 => match token {
				'0' => 24u32,
				_ => return false,
			},
			24u32 => match token {
				'0' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 26u32,
				_ => return false,
			},
			26u32 => match token {
				'0' => 27u32,
				_ => return false,
			},
			27u32 => match token {
				'0' => 28u32,
				_ => return false,
			},
			28u32 => match token {
				'+' | '-' => 29u32,
				'.' => 30u32,
				'Z' => 31u32,
				_ => return false,
			},
			29u32 => match token {
				'0' => 32u32,
				'1' => 33u32,
				_ => return false,
			},
			30u32 => match token {
				'0' => 34u32,
				_ => return false,
			},
			32u32 => match token {
				'0'..='9' => 35u32,
				_ => return false,
			},
			33u32 => match token {
				'0'..='3' => 35u32,
				'4' => 36u32,
				_ => return false,
			},
			34u32 => match token {
				'+' | '-' => 29u32,
				'0' => 34u32,
				'Z' => 31u32,
				_ => return false,
			},
			35u32 => match token {
				':' => 37u32,
				_ => return false,
			},
			36u32 => match token {
				':' => 38u32,
				_ => return false,
			},
			37u32 => match token {
				'0'..='5' => 40u32,
				_ => return false,
			},
			38u32 => match token {
				'0' => 39u32,
				_ => return false,
			},
			39u32 => match token {
				'0' => 31u32,
				_ => return false,
			},
			40u32 => match token {
				'0'..='9' => 31u32,
				_ => return false,
			},
			41u32 => match token {
				'0'..='9' => 42u32,
				_ => return false,
			},
			42u32 => match token {
				':' => 43u32,
				_ => return false,
			},
			43u32 => match token {
				'0'..='5' => 44u32,
				_ => return false,
			},
			44u32 => match token {
				'0'..='9' => 45u32,
				_ => return false,
			},
			45u32 => match token {
				'+' | '-' => 29u32,
				'.' => 46u32,
				'Z' => 31u32,
				_ => return false,
			},
			46u32 => match token {
				'0'..='9' => 47u32,
				_ => return false,
			},
			47u32 => match token {
				'+' | '-' => 29u32,
				'0'..='9' => 47u32,
				'Z' => 31u32,
				_ => return false,
			},
			48u32 => match token {
				'0'..='9' => 49u32,
				_ => return false,
			},
			49u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 28u32 | 31u32 | 34u32 | 45u32 | 47u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DateTimeStamp {
	state: u32,
}
impl DateTimeStamp {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 48u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 9u32,
				'1' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'1'..='9' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='2' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'-' => 12u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 13u32,
				'1'..='2' => 14u32,
				'3' => 15u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='9' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='1' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'T' => 17u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='1' => 18u32,
				'2' => 19u32,
				_ => return false,
			},
			18u32 => match token {
				'0'..='9' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='3' => 20u32,
				'4' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				':' => 22u32,
				_ => return false,
			},
			21u32 => match token {
				':' => 23u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='5' => 41u32,
				_ => return false,
			},
			23u32 => match token {
				'0' => 24u32,
				_ => return false,
			},
			24u32 => match token {
				'0' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 26u32,
				_ => return false,
			},
			26u32 => match token {
				'0' => 27u32,
				_ => return false,
			},
			27u32 => match token {
				'0' => 28u32,
				_ => return false,
			},
			28u32 => match token {
				'+' | '-' => 29u32,
				'.' => 30u32,
				'Z' => 31u32,
				_ => return false,
			},
			29u32 => match token {
				'0' => 32u32,
				'1' => 33u32,
				_ => return false,
			},
			30u32 => match token {
				'0' => 34u32,
				_ => return false,
			},
			32u32 => match token {
				'0'..='9' => 35u32,
				_ => return false,
			},
			33u32 => match token {
				'0'..='3' => 35u32,
				'4' => 36u32,
				_ => return false,
			},
			34u32 => match token {
				'+' | '-' => 29u32,
				'0' => 34u32,
				'Z' => 31u32,
				_ => return false,
			},
			35u32 => match token {
				':' => 37u32,
				_ => return false,
			},
			36u32 => match token {
				':' => 38u32,
				_ => return false,
			},
			37u32 => match token {
				'0'..='5' => 40u32,
				_ => return false,
			},
			38u32 => match token {
				'0' => 39u32,
				_ => return false,
			},
			39u32 => match token {
				'0' => 31u32,
				_ => return false,
			},
			40u32 => match token {
				'0'..='9' => 31u32,
				_ => return false,
			},
			41u32 => match token {
				'0'..='9' => 42u32,
				_ => return false,
			},
			42u32 => match token {
				':' => 43u32,
				_ => return false,
			},
			43u32 => match token {
				'0'..='5' => 44u32,
				_ => return false,
			},
			44u32 => match token {
				'0'..='9' => 45u32,
				_ => return false,
			},
			45u32 => match token {
				'+' | '-' => 29u32,
				'.' => 46u32,
				'Z' => 31u32,
				_ => return false,
			},
			46u32 => match token {
				'0'..='9' => 47u32,
				_ => return false,
			},
			47u32 => match token {
				'+' | '-' => 29u32,
				'0'..='9' => 47u32,
				'Z' => 31u32,
				_ => return false,
			},
			48u32 => match token {
				'0'..='9' => 49u32,
				_ => return false,
			},
			49u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 31u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Time {
	state: u32,
}
impl Time {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'0'..='1' => 1u32,
				'2' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='3' => 3u32,
				'4' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				':' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				':' => 6u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='5' => 24u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'0' => 8u32,
				_ => return false,
			},
			8u32 => match token {
				':' => 9u32,
				_ => return false,
			},
			9u32 => match token {
				'0' => 10u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'+' | '-' => 12u32,
				'.' => 13u32,
				'Z' => 14u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 15u32,
				'1' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'0' => 17u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='9' => 18u32,
				_ => return false,
			},
			16u32 => match token {
				'0'..='3' => 18u32,
				'4' => 19u32,
				_ => return false,
			},
			17u32 => match token {
				'+' | '-' => 12u32,
				'0' => 17u32,
				'Z' => 14u32,
				_ => return false,
			},
			18u32 => match token {
				':' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				':' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='5' => 23u32,
				_ => return false,
			},
			21u32 => match token {
				'0' => 22u32,
				_ => return false,
			},
			22u32 => match token {
				'0' => 14u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='9' => 14u32,
				_ => return false,
			},
			24u32 => match token {
				'0'..='9' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 26u32,
				_ => return false,
			},
			26u32 => match token {
				'0'..='5' => 27u32,
				_ => return false,
			},
			27u32 => match token {
				'0'..='9' => 28u32,
				_ => return false,
			},
			28u32 => match token {
				'+' | '-' => 12u32,
				'.' => 29u32,
				'Z' => 14u32,
				_ => return false,
			},
			29u32 => match token {
				'0'..='9' => 30u32,
				_ => return false,
			},
			30u32 => match token {
				'+' | '-' => 12u32,
				'0'..='9' => 30u32,
				'Z' => 14u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 11u32 | 14u32 | 17u32 | 28u32 | 30u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GDay {
	state: u32,
}
impl GDay {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'-' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'0' => 4u32,
				'1'..='2' => 5u32,
				'3' => 6u32,
				_ => return false,
			},
			4u32 => match token {
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='1' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 8u32,
				'Z' => 9u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 10u32,
				'1' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				'0'..='3' => 12u32,
				'4' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				':' => 14u32,
				_ => return false,
			},
			13u32 => match token {
				':' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='5' => 17u32,
				_ => return false,
			},
			15u32 => match token {
				'0' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'0' => 9u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='9' => 9u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 7u32 | 9u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GMonth {
	state: u32,
}
impl GMonth {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 3u32,
				'1' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'1'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='2' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'+' | '-' => 6u32,
				'Z' => 7u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 8u32,
				'1' => 9u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'0'..='3' => 10u32,
				'4' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				':' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				':' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='5' => 15u32,
				_ => return false,
			},
			13u32 => match token {
				'0' => 14u32,
				_ => return false,
			},
			14u32 => match token {
				'0' => 7u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 7u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GMonthDay {
	state: u32,
}
impl GMonthDay {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 3u32,
				'1' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'1'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='2' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'-' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 7u32,
				'1'..='2' => 8u32,
				'3' => 9u32,
				_ => return false,
			},
			7u32 => match token {
				'1'..='9' => 10u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'0'..='1' => 10u32,
				_ => return false,
			},
			10u32 => match token {
				'+' | '-' => 11u32,
				'Z' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				'0' => 13u32,
				'1' => 14u32,
				_ => return false,
			},
			13u32 => match token {
				'0'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='3' => 15u32,
				'4' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				':' => 17u32,
				_ => return false,
			},
			16u32 => match token {
				':' => 18u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='5' => 20u32,
				_ => return false,
			},
			18u32 => match token {
				'0' => 19u32,
				_ => return false,
			},
			19u32 => match token {
				'0' => 12u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 10u32 | 12u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GYear {
	state: u32,
}
impl GYear {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 18u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 7u32,
				'Z' => 9u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 10u32,
				'1' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				'0'..='3' => 12u32,
				'4' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				':' => 14u32,
				_ => return false,
			},
			13u32 => match token {
				':' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='5' => 17u32,
				_ => return false,
			},
			15u32 => match token {
				'0' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'0' => 9u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='9' => 9u32,
				_ => return false,
			},
			18u32 => match token {
				'0'..='9' => 19u32,
				_ => return false,
			},
			19u32 => match token {
				'+' | '-' => 8u32,
				'Z' => 9u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 7u32 | 9u32 | 19u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GYearMonth {
	state: u32,
}
impl GYearMonth {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 22u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 9u32,
				'1' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'1'..='9' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='2' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'+' | '-' => 12u32,
				'Z' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 14u32,
				'1' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='9' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='3' => 16u32,
				'4' => 17u32,
				_ => return false,
			},
			16u32 => match token {
				':' => 18u32,
				_ => return false,
			},
			17u32 => match token {
				':' => 19u32,
				_ => return false,
			},
			18u32 => match token {
				'0'..='5' => 21u32,
				_ => return false,
			},
			19u32 => match token {
				'0' => 20u32,
				_ => return false,
			},
			20u32 => match token {
				'0' => 13u32,
				_ => return false,
			},
			21u32 => match token {
				'0'..='9' => 13u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='9' => 23u32,
				_ => return false,
			},
			23u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 11u32 | 13u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Duration {
	state: u32,
}
impl Duration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				'T' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'D' => 5u32,
				'M' => 6u32,
				'Y' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'.' => 8u32,
				'0'..='9' => 9u32,
				_ => return false,
			},
			5u32 => match token {
				'T' => 4u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 16u32,
				'T' => 4u32,
				_ => return false,
			},
			7u32 => match token {
				'0'..='9' => 17u32,
				'T' => 4u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'.' => 10u32,
				'0'..='9' => 9u32,
				'H' => 11u32,
				'M' => 12u32,
				'S' => 13u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='9' => 10u32,
				'S' => 13u32,
				_ => return false,
			},
			11u32 => match token {
				'.' => 8u32,
				'0'..='9' => 14u32,
				_ => return false,
			},
			12u32 => match token {
				'.' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'.' => 10u32,
				'0'..='9' => 14u32,
				'M' => 12u32,
				'S' => 13u32,
				_ => return false,
			},
			15u32 => match token {
				'.' => 10u32,
				'0'..='9' => 15u32,
				'S' => 13u32,
				_ => return false,
			},
			16u32 => match token {
				'0'..='9' => 16u32,
				'D' => 5u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='9' => 17u32,
				'D' => 5u32,
				'M' => 6u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 6u32 | 7u32 | 11u32 | 12u32 | 13u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DayTimeDuration {
	state: u32,
}
impl DayTimeDuration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				'T' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'D' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'.' => 6u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'T' => 4u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 8u32,
				_ => return false,
			},
			7u32 => match token {
				'.' => 8u32,
				'0'..='9' => 7u32,
				'H' => 9u32,
				'M' => 10u32,
				'S' => 11u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 8u32,
				'S' => 11u32,
				_ => return false,
			},
			9u32 => match token {
				'.' => 6u32,
				'0'..='9' => 12u32,
				_ => return false,
			},
			10u32 => match token {
				'.' => 6u32,
				'0'..='9' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				'.' => 8u32,
				'0'..='9' => 12u32,
				'M' => 10u32,
				'S' => 11u32,
				_ => return false,
			},
			13u32 => match token {
				'.' => 8u32,
				'0'..='9' => 13u32,
				'S' => 11u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 9u32 | 10u32 | 11u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct YearMonthDuration {
	state: u32,
}
impl YearMonthDuration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'M' => 4u32,
				'Y' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 6u32,
				'M' => 4u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 4u32 | 5u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct QName {
	state: u32,
}
impl QName {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'A'..='Z'
				| '_'
				| 'a'..='z'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='˿'
				| 'Ͱ'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-'..='.'
				| '0'..='9'
				| 'A'..='Z'
				| '_'
				| 'a'..='z'
				| '·'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '‿'..='⁀'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 1u32,
				':' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'A'..='Z'
				| '_'
				| 'a'..='z'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='˿'
				| 'Ͱ'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'-'..='.'
				| '0'..='9'
				| 'A'..='Z'
				| '_'
				| 'a'..='z'
				| '·'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '‿'..='⁀'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 3u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 1u32 | 3u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Boolean {
	state: u32,
}
impl Boolean {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'0'..='1' => 1u32,
				'f' => 2u32,
				't' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'a' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'r' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'l' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'u' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'e' => 1u32,
				_ => return false,
			},
			7u32 => match token {
				's' => 6u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 1u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct HexBinary {
	state: u32,
}
impl HexBinary {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'0'..='9' | 'A'..='F' | 'a'..='f' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'0'..='9' | 'A'..='F' | 'a'..='f' => 0u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 0u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Base64Binary {
	state: u32,
}
impl Base64Binary {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				' ' => 2u32,
				'+' | '/'..='9' | 'B'..='P' | 'R'..='Z' | 'a'..='f' | 'h'..='v' | 'x'..='z' => 3u32,
				'A' | 'Q' | 'g' | 'w' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'+' | '/'..='9' | 'B'..='P' | 'R'..='Z' | 'a'..='f' | 'h'..='v' | 'x'..='z' => 3u32,
				'A' | 'Q' | 'g' | 'w' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				' ' => 5u32,
				'+'
				| '/'
				| '1'..='3'
				| '5'..='7'
				| '9'
				| 'B'..='D'
				| 'F'..='H'
				| 'J'..='L'
				| 'N'..='P'
				| 'R'..='T'
				| 'V'..='X'
				| 'Z'
				| 'a'..='b'
				| 'd'..='f'
				| 'h'..='j'
				| 'l'..='n'
				| 'p'..='r'
				| 't'..='v'
				| 'x'..='z' => 6u32,
				'0' | '4' | '8' | 'A' | 'E' | 'I' | 'M' | 'Q' | 'U' | 'Y' | 'c' | 'g' | 'k'
				| 'o' | 's' | 'w' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				' ' => 8u32,
				'+'
				| '/'
				| '1'..='3'
				| '5'..='7'
				| '9'
				| 'B'..='D'
				| 'F'..='H'
				| 'J'..='L'
				| 'N'..='P'
				| 'R'..='T'
				| 'V'..='X'
				| 'Z'
				| 'a'..='b'
				| 'd'..='f'
				| 'h'..='j'
				| 'l'..='n'
				| 'p'..='r'
				| 't'..='v'
				| 'x'..='z' => 6u32,
				'0' | '4' | '8' | 'A' | 'E' | 'I' | 'M' | 'Q' | 'U' | 'Y' | 'c' | 'g' | 'k'
				| 'o' | 's' | 'w' => 7u32,
				'=' => 9u32,
				_ => return false,
			},
			5u32 => match token {
				'+'
				| '/'
				| '1'..='3'
				| '5'..='7'
				| '9'
				| 'B'..='D'
				| 'F'..='H'
				| 'J'..='L'
				| 'N'..='P'
				| 'R'..='T'
				| 'V'..='X'
				| 'Z'
				| 'a'..='b'
				| 'd'..='f'
				| 'h'..='j'
				| 'l'..='n'
				| 'p'..='r'
				| 't'..='v'
				| 'x'..='z' => 6u32,
				'0' | '4' | '8' | 'A' | 'E' | 'I' | 'M' | 'Q' | 'U' | 'Y' | 'c' | 'g' | 'k'
				| 'o' | 's' | 'w' => 7u32,
				_ => return false,
			},
			6u32 => match token {
				' ' => 10u32,
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 11u32,
				_ => return false,
			},
			7u32 => match token {
				' ' => 12u32,
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 11u32,
				'=' => 13u32,
				_ => return false,
			},
			8u32 => match token {
				'+'
				| '/'
				| '1'..='3'
				| '5'..='7'
				| '9'
				| 'B'..='D'
				| 'F'..='H'
				| 'J'..='L'
				| 'N'..='P'
				| 'R'..='T'
				| 'V'..='X'
				| 'Z'
				| 'a'..='b'
				| 'd'..='f'
				| 'h'..='j'
				| 'l'..='n'
				| 'p'..='r'
				| 't'..='v'
				| 'x'..='z' => 6u32,
				'0' | '4' | '8' | 'A' | 'E' | 'I' | 'M' | 'Q' | 'U' | 'Y' | 'c' | 'g' | 'k'
				| 'o' | 's' | 'w' => 7u32,
				'=' => 9u32,
				_ => return false,
			},
			9u32 => match token {
				' ' => 15u32,
				'=' => 13u32,
				_ => return false,
			},
			10u32 => match token {
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				' ' => 14u32,
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 1u32,
				_ => return false,
			},
			12u32 => match token {
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 11u32,
				'=' => 13u32,
				_ => return false,
			},
			14u32 => match token {
				'+' | '/'..='9' | 'A'..='Z' | 'a'..='z' => 1u32,
				_ => return false,
			},
			15u32 => match token {
				'=' => 13u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 0u32 | 11u32 | 13u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Decimal {
	state: u32,
}
impl Decimal {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '-' => 1u32,
				'.' => 2u32,
				'0'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'.' => 2u32,
				'0'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'.' => 4u32,
				'0'..='9' => 3u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 3u32 | 4u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Integer {
	state: u32,
}
impl Integer {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '-' => 1u32,
				'0'..='9' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'0'..='9' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 2u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 2u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct NonNegativeInteger {
	state: u32,
}
impl NonNegativeInteger {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' => 1u32,
				'-' => 2u32,
				'0'..='9' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			4u32 => match token {
				'0' => 4u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 3u32 | 4u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct PositiveInteger {
	state: u32,
}
impl PositiveInteger {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '0' => 1u32,
				'1'..='9' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 1u32,
				'1'..='9' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 2u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 2u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct NonPositiveInteger {
	state: u32,
}
impl NonPositiveInteger {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' => 1u32,
				'-' => 2u32,
				'0' => 3u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0' => 3u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='9' => 4u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 3u32 | 4u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct NegativeInteger {
	state: u32,
}
impl NegativeInteger {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 1u32,
				'1'..='9' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 2u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 2u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Float {
	state: u32,
}
impl Float {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '-' => 1u32,
				'.' => 2u32,
				'0'..='9' => 3u32,
				'I' => 4u32,
				'N' => 5u32,
				_ => return false,
			},
			1u32 => match token {
				'.' => 2u32,
				'0'..='9' => 3u32,
				'I' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			3u32 => match token {
				'.' => 6u32,
				'0'..='9' => 3u32,
				'E' | 'e' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'N' => 8u32,
				_ => return false,
			},
			5u32 => match token {
				'a' => 9u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 6u32,
				'E' | 'e' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 11u32,
				'0'..='9' => 12u32,
				_ => return false,
			},
			8u32 => match token {
				'F' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'N' => 10u32,
				_ => return false,
			},
			11u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 3u32 | 6u32 | 10u32 | 12u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Double {
	state: u32,
}
impl Double {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'+' | '-' => 1u32,
				'.' => 2u32,
				'0'..='9' => 3u32,
				'I' => 4u32,
				'N' => 5u32,
				_ => return false,
			},
			1u32 => match token {
				'.' => 2u32,
				'0'..='9' => 3u32,
				'I' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			3u32 => match token {
				'.' => 6u32,
				'0'..='9' => 3u32,
				'E' | 'e' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'N' => 8u32,
				_ => return false,
			},
			5u32 => match token {
				'a' => 9u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 6u32,
				'E' | 'e' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 11u32,
				'0'..='9' => 12u32,
				_ => return false,
			},
			8u32 => match token {
				'F' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'N' => 10u32,
				_ => return false,
			},
			11u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 3u32 | 6u32 | 10u32 | 12u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
