/// This file is auto-generated by `static-automata`. Do not edit.
pub struct Date {
	state: u32,
}
impl Date {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='3' => 3u32,
				'4'..='9' => 4u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='4' => 3u32,
				'5'..='9' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 5u32,
				'1'..='4' => 6u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			3u32 => match token {
				'-' => 8u32,
				'0'..='4' => 9u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'-' => 8u32,
				'0' => 10u32,
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0' => 13u32,
				'1'..='9' => 33u32,
				_ => return false,
			},
			6u32 => match token {
				'-' => 8u32,
				'0'..='9' => 33u32,
				'5'..='9' => 35u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 11u32,
				'1' => 12u32,
				_ => return false,
			},
			9u32 => match token {
				'-' => 8u32,
				'0'..='4' => 32u32,
				'5'..='9' => 34u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			11u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='2' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'-' => 8u32,
				'1'..='9' => 15u32,
				_ => return false,
			},
			15u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			16u32 => match token {
				'-' => 17u32,
				_ => return false,
			},
			17u32 => match token {
				'0' => 18u32,
				'1'..='2' => 19u32,
				'3' => 20u32,
				_ => return false,
			},
			18u32 => match token {
				'1'..='9' => 21u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='9' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='1' => 21u32,
				_ => return false,
			},
			21u32 => match token {
				'+' | '-' => 22u32,
				'Z' => 23u32,
				_ => return false,
			},
			22u32 => match token {
				'0' => 24u32,
				'1' => 25u32,
				_ => return false,
			},
			24u32 => match token {
				'0'..='9' => 26u32,
				_ => return false,
			},
			25u32 => match token {
				'0'..='3' => 26u32,
				'4' => 27u32,
				_ => return false,
			},
			26u32 => match token {
				':' => 28u32,
				_ => return false,
			},
			27u32 => match token {
				':' => 29u32,
				_ => return false,
			},
			28u32 => match token {
				'0'..='5' => 31u32,
				_ => return false,
			},
			29u32 => match token {
				'0' => 30u32,
				_ => return false,
			},
			30u32 => match token {
				'0' => 23u32,
				_ => return false,
			},
			31u32 => match token {
				'0'..='9' => 23u32,
				_ => return false,
			},
			32u32 => match token {
				'-' => 8u32,
				'0'..='9' => 34u32,
				'6'..='9' => 15u32,
				_ => return false,
			},
			33u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			34u32 => match token {
				'-' => 8u32,
				'0'..='9' => 34u32,
				_ => return false,
			},
			35u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 21u32 | 23u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DateTime {
	state: u32,
}
impl DateTime {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='3' => 3u32,
				'4'..='9' => 4u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='4' => 3u32,
				'5'..='9' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 5u32,
				'1'..='4' => 6u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			3u32 => match token {
				'-' => 8u32,
				'0'..='4' => 9u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'-' => 8u32,
				'0' => 10u32,
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0' => 13u32,
				'1'..='9' => 54u32,
				_ => return false,
			},
			6u32 => match token {
				'-' => 8u32,
				'0'..='9' => 54u32,
				'5'..='9' => 56u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 11u32,
				'1' => 12u32,
				_ => return false,
			},
			9u32 => match token {
				'-' => 8u32,
				'0'..='4' => 53u32,
				'5'..='9' => 54u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			11u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='2' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'-' => 8u32,
				'1'..='9' => 15u32,
				_ => return false,
			},
			15u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			16u32 => match token {
				'-' => 17u32,
				_ => return false,
			},
			17u32 => match token {
				'0' => 18u32,
				'1'..='2' => 19u32,
				'3' => 20u32,
				_ => return false,
			},
			18u32 => match token {
				'1'..='9' => 21u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='9' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='1' => 21u32,
				_ => return false,
			},
			21u32 => match token {
				'T' => 22u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='1' => 23u32,
				'2' => 24u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='9' => 25u32,
				_ => return false,
			},
			24u32 => match token {
				'0'..='3' => 25u32,
				'4' => 26u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 27u32,
				_ => return false,
			},
			26u32 => match token {
				':' => 28u32,
				_ => return false,
			},
			27u32 => match token {
				'0'..='5' => 46u32,
				_ => return false,
			},
			28u32 => match token {
				'0' => 29u32,
				_ => return false,
			},
			29u32 => match token {
				'0' => 30u32,
				_ => return false,
			},
			30u32 => match token {
				':' => 31u32,
				_ => return false,
			},
			31u32 => match token {
				'0' => 32u32,
				_ => return false,
			},
			32u32 => match token {
				'0' => 33u32,
				_ => return false,
			},
			33u32 => match token {
				'+' | '-' => 34u32,
				'.' => 35u32,
				'Z' => 36u32,
				_ => return false,
			},
			34u32 => match token {
				'0' => 37u32,
				'1' => 38u32,
				_ => return false,
			},
			35u32 => match token {
				'0' => 39u32,
				_ => return false,
			},
			37u32 => match token {
				'0'..='9' => 40u32,
				_ => return false,
			},
			38u32 => match token {
				'0'..='3' => 40u32,
				'4' => 41u32,
				_ => return false,
			},
			39u32 => match token {
				'+' | '-' => 34u32,
				'0' => 39u32,
				'Z' => 36u32,
				_ => return false,
			},
			40u32 => match token {
				':' => 42u32,
				_ => return false,
			},
			41u32 => match token {
				':' => 43u32,
				_ => return false,
			},
			42u32 => match token {
				'0'..='5' => 45u32,
				_ => return false,
			},
			43u32 => match token {
				'0' => 44u32,
				_ => return false,
			},
			44u32 => match token {
				'0' => 36u32,
				_ => return false,
			},
			45u32 => match token {
				'0'..='9' => 36u32,
				_ => return false,
			},
			46u32 => match token {
				'0'..='9' => 47u32,
				_ => return false,
			},
			47u32 => match token {
				':' => 48u32,
				_ => return false,
			},
			48u32 => match token {
				'0'..='5' => 49u32,
				_ => return false,
			},
			49u32 => match token {
				'0'..='9' => 50u32,
				_ => return false,
			},
			50u32 => match token {
				'+' | '-' => 34u32,
				'.' => 51u32,
				'Z' => 36u32,
				_ => return false,
			},
			51u32 => match token {
				'0'..='9' => 52u32,
				_ => return false,
			},
			52u32 => match token {
				'+' | '-' => 34u32,
				'0'..='9' => 52u32,
				'Z' => 36u32,
				_ => return false,
			},
			53u32 => match token {
				'-' => 8u32,
				'0'..='9' => 55u32,
				'6'..='9' => 15u32,
				_ => return false,
			},
			54u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			55u32 => match token {
				'-' => 8u32,
				'0'..='9' => 55u32,
				_ => return false,
			},
			56u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 33u32 | 36u32 | 39u32 | 50u32 | 52u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DateTimeStamp {
	state: u32,
}
impl DateTimeStamp {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='3' => 3u32,
				'4'..='9' => 4u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='4' => 3u32,
				'5'..='9' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 5u32,
				'1'..='4' => 6u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			3u32 => match token {
				'-' => 8u32,
				'0'..='4' => 9u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'-' => 8u32,
				'0' => 10u32,
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0' => 13u32,
				'1'..='9' => 54u32,
				_ => return false,
			},
			6u32 => match token {
				'-' => 8u32,
				'0'..='9' => 54u32,
				'5'..='9' => 56u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 11u32,
				'1' => 12u32,
				_ => return false,
			},
			9u32 => match token {
				'-' => 8u32,
				'0'..='4' => 53u32,
				'5'..='9' => 54u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			11u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='2' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'-' => 8u32,
				'1'..='9' => 15u32,
				_ => return false,
			},
			15u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			16u32 => match token {
				'-' => 17u32,
				_ => return false,
			},
			17u32 => match token {
				'0' => 18u32,
				'1'..='2' => 19u32,
				'3' => 20u32,
				_ => return false,
			},
			18u32 => match token {
				'1'..='9' => 21u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='9' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='1' => 21u32,
				_ => return false,
			},
			21u32 => match token {
				'T' => 22u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='1' => 23u32,
				'2' => 24u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='9' => 25u32,
				_ => return false,
			},
			24u32 => match token {
				'0'..='3' => 25u32,
				'4' => 26u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 27u32,
				_ => return false,
			},
			26u32 => match token {
				':' => 28u32,
				_ => return false,
			},
			27u32 => match token {
				'0'..='5' => 46u32,
				_ => return false,
			},
			28u32 => match token {
				'0' => 29u32,
				_ => return false,
			},
			29u32 => match token {
				'0' => 30u32,
				_ => return false,
			},
			30u32 => match token {
				':' => 31u32,
				_ => return false,
			},
			31u32 => match token {
				'0' => 32u32,
				_ => return false,
			},
			32u32 => match token {
				'0' => 33u32,
				_ => return false,
			},
			33u32 => match token {
				'+' | '-' => 34u32,
				'.' => 35u32,
				'Z' => 36u32,
				_ => return false,
			},
			34u32 => match token {
				'0' => 37u32,
				'1' => 38u32,
				_ => return false,
			},
			35u32 => match token {
				'0' => 39u32,
				_ => return false,
			},
			37u32 => match token {
				'0'..='9' => 40u32,
				_ => return false,
			},
			38u32 => match token {
				'0'..='3' => 40u32,
				'4' => 41u32,
				_ => return false,
			},
			39u32 => match token {
				'+' | '-' => 34u32,
				'0' => 39u32,
				'Z' => 36u32,
				_ => return false,
			},
			40u32 => match token {
				':' => 42u32,
				_ => return false,
			},
			41u32 => match token {
				':' => 43u32,
				_ => return false,
			},
			42u32 => match token {
				'0'..='5' => 45u32,
				_ => return false,
			},
			43u32 => match token {
				'0' => 44u32,
				_ => return false,
			},
			44u32 => match token {
				'0' => 36u32,
				_ => return false,
			},
			45u32 => match token {
				'0'..='9' => 36u32,
				_ => return false,
			},
			46u32 => match token {
				'0'..='9' => 47u32,
				_ => return false,
			},
			47u32 => match token {
				':' => 48u32,
				_ => return false,
			},
			48u32 => match token {
				'0'..='5' => 49u32,
				_ => return false,
			},
			49u32 => match token {
				'0'..='9' => 50u32,
				_ => return false,
			},
			50u32 => match token {
				'+' | '-' => 34u32,
				'.' => 51u32,
				'Z' => 36u32,
				_ => return false,
			},
			51u32 => match token {
				'0'..='9' => 52u32,
				_ => return false,
			},
			52u32 => match token {
				'+' | '-' => 34u32,
				'0'..='9' => 52u32,
				'Z' => 36u32,
				_ => return false,
			},
			53u32 => match token {
				'-' => 8u32,
				'0'..='9' => 55u32,
				'6'..='9' => 15u32,
				_ => return false,
			},
			54u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			55u32 => match token {
				'-' => 8u32,
				'0'..='9' => 55u32,
				_ => return false,
			},
			56u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 36u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Time {
	state: u32,
}
impl Time {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'0'..='1' => 1u32,
				'2' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='3' => 3u32,
				'4' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				':' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				':' => 6u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='5' => 24u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'0' => 8u32,
				_ => return false,
			},
			8u32 => match token {
				':' => 9u32,
				_ => return false,
			},
			9u32 => match token {
				'0' => 10u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 11u32,
				_ => return false,
			},
			11u32 => match token {
				'+' | '-' => 12u32,
				'.' => 13u32,
				'Z' => 14u32,
				_ => return false,
			},
			12u32 => match token {
				'0' => 15u32,
				'1' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'0' => 17u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='9' => 18u32,
				_ => return false,
			},
			16u32 => match token {
				'0'..='3' => 18u32,
				'4' => 19u32,
				_ => return false,
			},
			17u32 => match token {
				'+' | '-' => 12u32,
				'0' => 17u32,
				'Z' => 14u32,
				_ => return false,
			},
			18u32 => match token {
				':' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				':' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='5' => 23u32,
				_ => return false,
			},
			21u32 => match token {
				'0' => 22u32,
				_ => return false,
			},
			22u32 => match token {
				'0' => 14u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='9' => 14u32,
				_ => return false,
			},
			24u32 => match token {
				'0'..='9' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				':' => 26u32,
				_ => return false,
			},
			26u32 => match token {
				'0'..='5' => 27u32,
				_ => return false,
			},
			27u32 => match token {
				'0'..='9' => 28u32,
				_ => return false,
			},
			28u32 => match token {
				'+' | '-' => 12u32,
				'.' => 29u32,
				'Z' => 14u32,
				_ => return false,
			},
			29u32 => match token {
				'0'..='9' => 30u32,
				_ => return false,
			},
			30u32 => match token {
				'+' | '-' => 12u32,
				'0'..='9' => 30u32,
				'Z' => 14u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 11u32 | 14u32 | 17u32 | 28u32 | 30u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GDay {
	state: u32,
}
impl GDay {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'-' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'0' => 4u32,
				'1'..='2' => 5u32,
				'3' => 6u32,
				_ => return false,
			},
			4u32 => match token {
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='1' => 7u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 8u32,
				'Z' => 9u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 10u32,
				'1' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				'0'..='3' => 12u32,
				'4' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				':' => 14u32,
				_ => return false,
			},
			13u32 => match token {
				':' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='5' => 17u32,
				_ => return false,
			},
			15u32 => match token {
				'0' => 16u32,
				_ => return false,
			},
			16u32 => match token {
				'0' => 9u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='9' => 9u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 7u32 | 9u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GMonth {
	state: u32,
}
impl GMonth {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 3u32,
				'1' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'1'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='2' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'+' | '-' => 6u32,
				'Z' => 7u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 8u32,
				'1' => 9u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'0'..='3' => 10u32,
				'4' => 11u32,
				_ => return false,
			},
			10u32 => match token {
				':' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				':' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='5' => 15u32,
				_ => return false,
			},
			13u32 => match token {
				'0' => 14u32,
				_ => return false,
			},
			14u32 => match token {
				'0' => 7u32,
				_ => return false,
			},
			15u32 => match token {
				'0'..='9' => 7u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 7u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GMonthDay {
	state: u32,
}
impl GMonthDay {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 3u32,
				'1' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'1'..='9' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'0'..='2' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'-' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0' => 7u32,
				'1'..='2' => 8u32,
				'3' => 9u32,
				_ => return false,
			},
			7u32 => match token {
				'1'..='9' => 10u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'0'..='1' => 10u32,
				_ => return false,
			},
			10u32 => match token {
				'+' | '-' => 11u32,
				'Z' => 12u32,
				_ => return false,
			},
			11u32 => match token {
				'0' => 13u32,
				'1' => 14u32,
				_ => return false,
			},
			13u32 => match token {
				'0'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'0'..='3' => 15u32,
				'4' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				':' => 17u32,
				_ => return false,
			},
			16u32 => match token {
				':' => 18u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='5' => 20u32,
				_ => return false,
			},
			18u32 => match token {
				'0' => 19u32,
				_ => return false,
			},
			19u32 => match token {
				'0' => 12u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='9' => 12u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 10u32 | 12u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GYear {
	state: u32,
}
impl GYear {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='3' => 3u32,
				'4'..='9' => 4u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='4' => 3u32,
				'5'..='9' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 5u32,
				'1'..='4' => 6u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			3u32 => match token {
				'+' | '-' => 8u32,
				'0'..='4' => 9u32,
				'5'..='9' => 7u32,
				'Z' => 10u32,
				_ => return false,
			},
			4u32 => match token {
				'+' | '-' => 8u32,
				'0' => 11u32,
				'1'..='9' => 7u32,
				'Z' => 10u32,
				_ => return false,
			},
			5u32 => match token {
				'0' => 14u32,
				'1'..='9' => 24u32,
				_ => return false,
			},
			6u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 24u32,
				'5'..='9' => 26u32,
				'Z' => 10u32,
				_ => return false,
			},
			7u32 => match token {
				'+' | '-' => 8u32,
				'0' => 14u32,
				'1'..='9' => 15u32,
				'Z' => 10u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 12u32,
				'1' => 13u32,
				_ => return false,
			},
			9u32 => match token {
				'+' | '-' => 8u32,
				'0'..='4' => 23u32,
				'5'..='9' => 25u32,
				'Z' => 10u32,
				_ => return false,
			},
			11u32 => match token {
				'0' => 14u32,
				'1'..='9' => 15u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='9' => 17u32,
				_ => return false,
			},
			13u32 => match token {
				'0'..='3' => 17u32,
				'4' => 18u32,
				_ => return false,
			},
			14u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			15u32 => match token {
				'+' | '-' => 8u32,
				'1'..='9' => 16u32,
				'Z' => 10u32,
				_ => return false,
			},
			16u32 => match token {
				'+' | '-' => 8u32,
				'Z' => 10u32,
				_ => return false,
			},
			17u32 => match token {
				':' => 19u32,
				_ => return false,
			},
			18u32 => match token {
				':' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='5' => 22u32,
				_ => return false,
			},
			20u32 => match token {
				'0' => 21u32,
				_ => return false,
			},
			21u32 => match token {
				'0' => 10u32,
				_ => return false,
			},
			22u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			23u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 25u32,
				'6'..='9' => 16u32,
				'Z' => 10u32,
				_ => return false,
			},
			24u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 16u32,
				'Z' => 10u32,
				_ => return false,
			},
			25u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 25u32,
				'Z' => 10u32,
				_ => return false,
			},
			26u32 => match token {
				'+' | '-' => 8u32,
				'0'..='9' => 16u32,
				'Z' => 10u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(
			self.state,
			3u32 | 4u32
				| 6u32 | 7u32
				| 9u32 | 10u32
				| 15u32 | 16u32
				| 23u32 | 24u32
				| 25u32 | 26u32
		)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct GYearMonth {
	state: u32,
}
impl GYearMonth {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'0' => 2u32,
				'1'..='3' => 3u32,
				'4'..='9' => 4u32,
				_ => return false,
			},
			1u32 => match token {
				'0' => 2u32,
				'1'..='4' => 3u32,
				'5'..='9' => 4u32,
				_ => return false,
			},
			2u32 => match token {
				'0' => 5u32,
				'1'..='4' => 6u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			3u32 => match token {
				'-' => 8u32,
				'0'..='4' => 9u32,
				'5'..='9' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'-' => 8u32,
				'0' => 10u32,
				'1'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'0' => 13u32,
				'1'..='9' => 28u32,
				_ => return false,
			},
			6u32 => match token {
				'-' => 8u32,
				'0'..='9' => 28u32,
				'5'..='9' => 30u32,
				_ => return false,
			},
			7u32 => match token {
				'-' => 8u32,
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			8u32 => match token {
				'0' => 11u32,
				'1' => 12u32,
				_ => return false,
			},
			9u32 => match token {
				'-' => 8u32,
				'0'..='4' => 27u32,
				'5'..='9' => 28u32,
				_ => return false,
			},
			10u32 => match token {
				'0' => 13u32,
				'1'..='9' => 14u32,
				_ => return false,
			},
			11u32 => match token {
				'1'..='9' => 16u32,
				_ => return false,
			},
			12u32 => match token {
				'0'..='2' => 16u32,
				_ => return false,
			},
			13u32 => match token {
				'1'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'-' => 8u32,
				'1'..='9' => 15u32,
				_ => return false,
			},
			15u32 => match token {
				'-' => 8u32,
				_ => return false,
			},
			16u32 => match token {
				'+' | '-' => 17u32,
				'Z' => 18u32,
				_ => return false,
			},
			17u32 => match token {
				'0' => 19u32,
				'1' => 20u32,
				_ => return false,
			},
			19u32 => match token {
				'0'..='9' => 21u32,
				_ => return false,
			},
			20u32 => match token {
				'0'..='3' => 21u32,
				'4' => 22u32,
				_ => return false,
			},
			21u32 => match token {
				':' => 23u32,
				_ => return false,
			},
			22u32 => match token {
				':' => 24u32,
				_ => return false,
			},
			23u32 => match token {
				'0'..='5' => 26u32,
				_ => return false,
			},
			24u32 => match token {
				'0' => 25u32,
				_ => return false,
			},
			25u32 => match token {
				'0' => 18u32,
				_ => return false,
			},
			26u32 => match token {
				'0'..='9' => 18u32,
				_ => return false,
			},
			27u32 => match token {
				'-' => 8u32,
				'0'..='9' => 29u32,
				'6'..='9' => 15u32,
				_ => return false,
			},
			28u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			29u32 => match token {
				'-' => 8u32,
				'0'..='9' => 29u32,
				_ => return false,
			},
			30u32 => match token {
				'-' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 16u32 | 18u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct Duration {
	state: u32,
}
impl Duration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				'T' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'D' => 5u32,
				'M' => 6u32,
				'Y' => 7u32,
				_ => return false,
			},
			4u32 => match token {
				'.' => 8u32,
				'0'..='9' => 9u32,
				_ => return false,
			},
			5u32 => match token {
				'T' => 4u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 16u32,
				'T' => 4u32,
				_ => return false,
			},
			7u32 => match token {
				'0'..='9' => 17u32,
				'T' => 4u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 10u32,
				_ => return false,
			},
			9u32 => match token {
				'.' => 10u32,
				'0'..='9' => 9u32,
				'H' => 11u32,
				'M' => 12u32,
				'S' => 13u32,
				_ => return false,
			},
			10u32 => match token {
				'0'..='9' => 10u32,
				'S' => 13u32,
				_ => return false,
			},
			11u32 => match token {
				'.' => 8u32,
				'0'..='9' => 14u32,
				_ => return false,
			},
			12u32 => match token {
				'.' => 8u32,
				'0'..='9' => 15u32,
				_ => return false,
			},
			14u32 => match token {
				'.' => 10u32,
				'0'..='9' => 14u32,
				'M' => 12u32,
				'S' => 13u32,
				_ => return false,
			},
			15u32 => match token {
				'.' => 10u32,
				'0'..='9' => 15u32,
				'S' => 13u32,
				_ => return false,
			},
			16u32 => match token {
				'0'..='9' => 16u32,
				'D' => 5u32,
				_ => return false,
			},
			17u32 => match token {
				'0'..='9' => 17u32,
				'D' => 5u32,
				'M' => 6u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 6u32 | 7u32 | 11u32 | 12u32 | 13u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct DayTimeDuration {
	state: u32,
}
impl DayTimeDuration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				'T' => 4u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'D' => 5u32,
				_ => return false,
			},
			4u32 => match token {
				'.' => 6u32,
				'0'..='9' => 7u32,
				_ => return false,
			},
			5u32 => match token {
				'T' => 4u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 8u32,
				_ => return false,
			},
			7u32 => match token {
				'.' => 8u32,
				'0'..='9' => 7u32,
				'H' => 9u32,
				'M' => 10u32,
				'S' => 11u32,
				_ => return false,
			},
			8u32 => match token {
				'0'..='9' => 8u32,
				'S' => 11u32,
				_ => return false,
			},
			9u32 => match token {
				'.' => 6u32,
				'0'..='9' => 12u32,
				_ => return false,
			},
			10u32 => match token {
				'.' => 6u32,
				'0'..='9' => 13u32,
				_ => return false,
			},
			12u32 => match token {
				'.' => 8u32,
				'0'..='9' => 12u32,
				'M' => 10u32,
				'S' => 11u32,
				_ => return false,
			},
			13u32 => match token {
				'.' => 8u32,
				'0'..='9' => 13u32,
				'S' => 11u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 5u32 | 9u32 | 10u32 | 11u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct YearMonthDuration {
	state: u32,
}
impl YearMonthDuration {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'-' => 1u32,
				'P' => 2u32,
				_ => return false,
			},
			1u32 => match token {
				'P' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'0'..='9' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'0'..='9' => 3u32,
				'M' => 4u32,
				'Y' => 5u32,
				_ => return false,
			},
			5u32 => match token {
				'0'..='9' => 6u32,
				_ => return false,
			},
			6u32 => match token {
				'0'..='9' => 6u32,
				'M' => 4u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 4u32 | 5u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
pub struct QName {
	state: u32,
}
impl QName {
	pub const fn new() -> Self {
		Self { state: 0u32 }
	}
	pub const fn push(&mut self, token: char) -> bool {
		self.state = match self.state {
			0u32 => match token {
				'A'..='Z'
				| '_'
				| 'a'..='z'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='˿'
				| 'Ͱ'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 1u32,
				_ => return false,
			},
			1u32 => match token {
				'-'..='.'
				| '0'..='9'
				| 'A'..='Z'
				| '_'
				| 'a'..='z'
				| '·'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '‿'..='⁀'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 1u32,
				':' => 2u32,
				_ => return false,
			},
			2u32 => match token {
				'A'..='Z'
				| '_'
				| 'a'..='z'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='˿'
				| 'Ͱ'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 3u32,
				_ => return false,
			},
			3u32 => match token {
				'-'..='.'
				| '0'..='9'
				| 'A'..='Z'
				| '_'
				| 'a'..='z'
				| '·'
				| 'À'..='Ö'
				| 'Ø'..='ö'
				| 'ø'..='ͽ'
				| 'Ϳ'..='\u{1fff}'
				| '\u{200c}'..='\u{200d}'
				| '‿'..='⁀'
				| '⁰'..='\u{218f}'
				| 'Ⰰ'..='\u{2fef}'
				| '、'..='\u{d7ff}'
				| '豈'..='﷏'
				| 'ﷰ'..='�'
				| '𐀀'..='\u{effff}' => 3u32,
				_ => return false,
			},
			_ => return false,
		};
		true
	}
	pub const fn is_accepting(&self) -> bool {
		matches!(self.state, 1u32 | 3u32)
	}
	pub const fn validate_str(s: &str) -> bool {
		Self::validate_bytes(s.as_bytes())
	}
	pub const fn validate_bytes(bytes: &[u8]) -> bool {
		let mut i = 0;
		let mut automaton = Self::new();
		while i < bytes.len() {
			match ::static_automata::decode_utf8_char(bytes, i) {
				Ok((c, len)) => {
					if !automaton.push(c) {
						return false;
					}
					i += len;
				}
				Err(_) => return false,
			}
		}
		automaton.is_accepting()
	}
}
